_target_: src.models.gcpnet_ar_module.GCPNetARLitModule

layer_class:
  _target_: src.models.components.gcpnet.GCPInteractions2
  _partial_: true
  updating_node_positions: true

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  betas: [0.9, 0.999]
  weight_decay: 1e-3

scheduler:  # note: leaving `scheduler` empty will result in a learning-rate scheduler not being used
  # _target_: torch.optim.lr_scheduler.StepLR
  # _partial_: true
  # step_size: ${...trainer.min_epochs} // 8  # note: using literal evalution manually until Hydra natively supports this functionality
  # gamma: 0.9
  # last_epoch: -1

defaults:
  - model_cfg: gcp_model_ar.yaml
  - module_cfg: gcp_module_ar.yaml
  - layer_cfg: gcp_interaction_layer_ar.yaml
