selected_GCP:
  # which version of the GCP module to use (e.g., GCP or GCP2)
  _target_: src.models.components.gcpnet.GCP2
  _partial_: true

concatenate_lig_flag: false
norm_x_diff: true

scalar_gate: 0
vector_gate: true  # note: For both GCP and GCP2, this parameter is used;   For GCP2, this mimics updating vector features without directly using frame vectors
vector_residual: false  # note: For both GCP and GCP2, this parameter is used
vector_frame_residual: false  # note: for GCP2, this parameter is unused
frame_gate: false  # note: for GCP2, if this parameter and `vector_gate` are both set to `false`, row-wise vector self-gating is applied instead
sigma_frame_gate: false  # note: For GCP, this parameter overrides `frame_gate`;   For GCP2, this parameter is unused and is replaced in functionality by `vector_gate`

scalar_nonlinearity: relu
vector_nonlinearity: 

nonlinearities:
  - ${..scalar_nonlinearity}
  - ${..vector_nonlinearity}

bottleneck: 4

vector_linear: true
vector_identity: true

default_vector_residual: false
default_bottleneck: 4

ablate_frame_updates: false