# @package _global_

defaults:
  - _self_
  - datamodule: atom3d_lba.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: gcpnet_lba.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???

# seed for random number generators in pytorch, numpy and python.random
seed: 42

# note: for WandB logging from certain remote GPU servers
create_unverified_ssl_context: false