_target_: src.datamodules.eq_datamodule.EQDataModule
splits_dir: ${paths.data_dir}/EQ/splits
decoy_dir: ${paths.data_dir}/EQ/decoy_model
true_dir: ${paths.data_dir}/EQ/true_model
model_data_cache_dir: ${paths.data_dir}/EQ/model_data_cache
edge_cutoff: 4.5
max_neighbors: 32
rbf_edge_dist_cutoff: 4.5  # note: units are in Angstrom
num_rbf: 16
python_exec_path:  # note: providing a value for `python_exec_path` is required when also providing a value for `pdbtools_dir`, to run `pdb-tools`
lddt_exec_path:  # note: leaving `lddt_exec_path` as null will have the `ARDataset` run `lDDT` CLI-directly
pdbtools_dir:  # note: leaving `pdbtools_dir` as null will have the `ARDataset` run `pdb-tools` CLI-directly
subset_to_ca_atoms_only: false  # note: set to `true` to convert a model into its `*_residue` equivalent
batch_size: 1
num_workers: 4
pin_memory: false
# arguments for model inference
predict_input_dir: ${paths.data_dir}/EQ/examples/decoy_model
predict_true_dir: ${paths.data_dir}/EQ/examples/true_model
predict_output_dir: ${paths.data_dir}/EQ/examples/outputs
predict_batch_size: 1
predict_pin_memory: false