_target_: src.datamodules.nms_datamodule.NMSDataModule

data_dir: ${paths.data_dir}NMS
data_mode: small
max_units: 0
unit: edge
rbf_edge_dist_cutoff: 4.5
num_rbf: 16
frame_O: 30
frame_T: 40
batch_size: 100
num_workers: 4
pin_memory: true
